name: gql
version: 0.1.0.0
github: "jonathanlorimer/gql"
license: BSD3
author: "Jonathan Lorimer"
maintainer: "jonathan_lorimer@mac.com"
copyright: "2019 Jonathan Lorimer"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jonathanlorimer/gql#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - aeson
  - microlens
  - microlens-aeson
  - attoparsec
  - containers
  - warp
  - wai
  - http-types
  - pretty
  - QuickCheck
  - hspec
  - parser-combinators
  - mtl

default-extensions:
  - DeriveGeneric
  - TypeFamilies
  - RankNTypes
  - GADTs
  - DataKinds
  - PolyKinds
  - ScopedTypeVariables
  - TypeApplications
  - MultiParamTypeClasses
  - AllowAmbiguousTypes
  - TypeOperators
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - StandaloneDeriving
  - ConstraintKinds
  - UndecidableInstances
  - OverloadedStrings



library:
  source-dirs: src
  ghc-options: -Wall

tests:
  gql-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - hspec-discover >= 2.0
    dependencies:
      - gql
