name: weft
version: 0.1.0.0
github: "jonathanlorimer/weft"
license: BSD3
author: "Jonathan Lorimer"
maintainer: "jonathan_lorimer@mac.com"
copyright: "2019 Jonathan Lorimer"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jonathanlorimer/weft#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - aeson
  - microlens
  - microlens-aeson
  - megaparsec
  - containers
  - warp
  - wai
  - wai-cors
  - http-types
  - pretty
  - QuickCheck
  - hspec
  - unordered-containers
  - parser-combinators
  - mtl

default-extensions:
  - DeriveGeneric
  - DerivingVia
  - TypeFamilies
  - RankNTypes
  - GADTs
  - DataKinds
  - PolyKinds
  - ScopedTypeVariables
  - TypeApplications
  - MultiParamTypeClasses
  - AllowAmbiguousTypes
  - TypeOperators
  - FlexibleInstances
  - FlexibleContexts
  - FunctionalDependencies
  - StandaloneDeriving
  - ConstraintKinds
  - UndecidableInstances
  - OverloadedStrings

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -Wall
      - -Wredundant-constraints
    dependencies:
      - weft

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - hspec-discover >= 2.0
    dependencies:
      - weft
